openproblems-bio/openproblems

.github/workflows/run_benchmark.yml
.gitmodules

As updated in this commit: https://github.com/singlecellopenproblems/SingleCellOpenProblems/commit/f1c84cbb64bdc3a183d6365b4a7cb85411f015c8, it is possible to run nextflow pipelines from a GitHub repository, which will automatically pull down the GitHub code.
Can pull a branch with `-r branchname`:
```
nextflow run owner/repo -r branchname
```
Can pull a hash (as this commit does: https://github.com/singlecellopenproblems/SingleCellOpenProblems/commit/f1c84cbb64bdc3a183d6365b4a7cb85411f015c8)
```
nextflow run owner/repo -r hash123
```
Can specify the branch and always pull the latest version:
```
nextflow run owner/repo -r main -latest
```
Hope that helps!

Remove nf-openproblems git submodule

---

CONTRIBUTING.md
docker/openproblems-python-extras/requirements.txt
openproblems/tasks/multimodal_data_integration/methods/scot.py

This PR adds the Single-cell Optimal Transport method to the multimodal integration task. 
Some potential questions:
* I have a long URL link that fails our `flake8` test, this is useful for documenting where these parameters came from. 
* There are a number of options on exactly what to compare existing methods use two normalization schemes, for SCOT I included both of these as well as the `balanced` option, which is quite important (as it represents separate but important variants of the Gromov-Wasserstein distance). 
* SCOT is not well packaged, therefore I had to do my own packaging and so we currently install `SCOT` via my forked repository. I have submitted a [PR](https://github.com/rsinghlab/SCOT/pull/4) on the SCOT [GitHub](https://github.com/rsinghlab/SCOT), if this is merged up …

Add Method SCOT to Multi-modal data Integration Task

---

.gitignore
openproblems/tasks/dimensionality_reduction/README.md
openproblems/tasks/dimensionality_reduction/metrics/__init__.py
openproblems/tasks/dimensionality_reduction/metrics/trustworthiness.py
test/test_metrics.py

https://github.com/michalk8/SingleCellOpenProblems/actions/runs/698892182
This PR adds trustworthiness score from `sklearn`.
Things that need to be resolved:
- the method does not work if there are non-finite values in the embedding/original space. Current solution: if original space contains non-fin. values (e.g. NaN), return NaN,
if the embedding contains these values, 0 is return (lowest possible value for the score).
- locally, I've tested that it works also on sparse matrices (in case adata.X), but haven't added any test for this: should the test be added in `test_metrics.py`?
- following the RMSE-based score, I've also saved the trust. score to `adata.uns['trustworthiness_score']` - is this desired?
closes #254

Add trustworthiness score for dimred task

---

openproblems/tasks/dimensionality_reduction/README.md
openproblems/tasks/dimensionality_reduction/methods/__init__.py
openproblems/tasks/dimensionality_reduction/methods/pca.py
openproblems/tasks/dimensionality_reduction/methods/phate.py
openproblems/tasks/dimensionality_reduction/methods/preprocessing.py
openproblems/tasks/dimensionality_reduction/methods/tsne.py
openproblems/tasks/dimensionality_reduction/methods/umap.py

Take 2 at adding standard pre-processing to the dimensionality (2D) task, replacing #289.
This submission modifies the dimensionality reduction (2D) task to include a script with standard pre-processing functions for use by methods (See #279). These should store a transformed expression matrix in `adata.X` and a higher dimensional embedding in `adata.obsm['X_input']` which is then used as the input for (most) methods.
* Add a `preprocessing.py` function that has pre-processing functions (one currently)
* Added that pre-processing function to the existing methods
* Created a new variant of **PHATE** that uses the standard pre-processing
* Updated the README to describe the pre-processing step

Dimred methods preprocessing

---

docker/openproblems-r-base/Dockerfile

A new key for the R repo (see https://cloud.r-project.org/) breaks building the R container.
This PR fixes that.

New key breaks r docker container build

---

setup.py

This is a temporary fix until I get access to the main repo of scprep to merge this feature.
Multiple PRs have been held up by poor error tracing in R -- this fix includes a printed traceback in all `RFunction` errors, which should greatly improve error readability.
Benchmark passed: https://github.com/scottgigante-immunai/openproblems/runs/6242627739?check_suite_focus=true

Use branch of scprep to provide R traceback

---

openproblems/tasks/dimensionality_reduction/methods/neuralee.py

NeuralEE takes ~10 minutes on test datasets. This should speed it up.

set maxit on neuralee

---

test/utils/docker.py

`timeout` is not present on all systems. This presents a system-agnostic fix.

handle missing timeout function

---

.github/workflows/run_tests.yml
test/test_methods.py
test/utils/docker.py

maxfail was added by accident. Printing durations will help use triage which tests need to be shortened.

remove maxfail; print durations

---

test/utils/docker.py
test/utils/exceptions.py
test/utils/run.py

We had two concurrent timeout mechanisms, one with `subprocess.poll` and one with `timeout`. Since `timeout` does not give a helpful error message, I am removing it in favour of the pure python solution.

remove redundant timeout infra

---

docker/openproblems/Dockerfile

Right at the moment when I pinned all of our packages, a python update broke everything 🤦 . This fixes that.

Pin python to 3.8.12

---

.github/workflows/run_tests.yml
docker/openproblems-python-batch-integration/Dockerfile

Docker 20.10.17 was released last week. Local builds are functioning while cloud builds are failing; maybe it's docker's fault.

Specify docker version

---

CONTRIBUTING.md
openproblems/api/README.md
openproblems/api/main.py
openproblems/api/parser.py
openproblems/api/test.py
openproblems/api/utils.py
openproblems/data/utils.py
openproblems/tasks/_batch_integration/batch_integration_graph/api.py
openproblems/tasks/_batch_integration/batch_integration_graph/methods/_utils.py
openproblems/tasks/_batch_integration/batch_integration_graph/methods/mnn.py
openproblems/tasks/_batch_integration/batch_integration_graph/methods/scanorama.py
openproblems/tasks/denoising/api.py
openproblems/tasks/dimensionality_reduction/api.py
openproblems/tasks/label_projection/api.py
openproblems/tasks/multimodal_data_integration/api.py
openproblems/tasks/regulatory_effect_prediction/api.py
openproblems/tools/decorators.py
test/test_0_tasks.py
test/test_3_datasets.py
test/test_5_cli.py

I realise in writing #468 that there is no straightforward way to test the performance of a new method. This PR adds a function to the CLI, `openproblems-cli test`, which allows straightforward testing of a method's performance with a specific dataset and metric. e.g.
```
openproblems-cli -t label_projection --dataset zebrafish_labels --method logistic_regression_log_cpm --metric accuracy
```
which will allow for simpler hyperparameter optimization by method devs.

Add CLI test for method optimization

---

docker/openproblems-python-tf2.4/requirements.txt

DCA uses tensorflow instead of tensorflow-cpu. This fixes that.

require tensorflow-cpu

---

docker/openproblems-python-scvi/requirements.txt

This adds xgboost to the scvi docker image for an scvi+scarches+xgboost label projection method.

add xgb to scvi docker image

---

openproblems/tasks/denoising/methods/alra.py
openproblems/tasks/denoising/methods/no_denoising.py
openproblems/tasks/dimensionality_reduction/methods/pca.py
openproblems/tasks/label_projection/methods/scvi_tools.py
openproblems/tasks/multimodal_data_integration/methods/harmonic_alignment.py
openproblems/tasks/spatial_decomposition/methods/nmfreg.py
openproblems/tasks/spatial_decomposition/methods/nnls.py
test/utils/asserts.py

Re-polling URLs too many times leads to 403 errors. This should reduce the risk of that by polling each URL at most once.

Cache result of `assert_url_accessible`

---

openproblems/tasks/spatial_decomposition/README.md
openproblems/tasks/spatial_decomposition/api.py
openproblems/tasks/spatial_decomposition/datasets/utils.py
openproblems/tasks/spatial_decomposition/methods/rctd.py

RCTD was failing due to some datasets having <25 cells for a given celltype label. Since this is a reasonable requirement, @LuckyMD and I decided we should just enforce it as part of the task API rather than try to fix RCTD to run even in the presence of rare celltypes.
cc @giovp

Require minimum celltype count for `spatial_decomposition`

---

openproblems/tasks/spatial_decomposition/methods/seuratv3.R
openproblems/tasks/spatial_decomposition/methods/seuratv3.py
openproblems/tasks/spatial_decomposition/methods/seuratv3_wrapper.R

Per https://tower.nf/orgs/openproblems-bio/workspaces/openproblems-bio/watch/2l0QkJPEKCHUCC , Seuratv3 is hanging with large datasets. Trial by error showed that running from a fork, rather than in rpy2, solved the problem. This is suboptimal because it requires writing and reading from disk which wastes some time, but hey, it works.
Requesting review from @giovp

Run seuratv3 from a fork

---

setup.py

igraph 0.10 (release September 6) is causing errors with louvain, e.g.
```
=================================== FAILURES ===================================
_ test_metric_batch_integration_graph_ari_openproblems_python_batch_integration _
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/parameterized/parameterized.py", line 533, in standalone_func
return func(*(a + p.args), **p.kwargs)
File "<decorator-gen-55>", line 2, in test_metric
File "/__w/openproblems/openproblems/test/utils/docker.py", line 267, in docker_test
run_image(image, f, timeout=timeout, retries=retries)
File "/__w/openproblems/openproblems/test/utils/docker.py", line 223, in run_image
return run.run(command, timeout=timeout)
File "/__w/openproblems/openproblems/test/utils/run.py", line 116, …
```

Pin igraph to 0.9

---

workflow/parse_nextflow.py

In theory, the website should short the table. However, having the JSON in sorted order is a helpful fallback.

Sort rank in processed output

---

openproblems/tasks/label_projection/methods/seurat.R
openproblems/tasks/spatial_decomposition/methods/seuratv3.R

When seurat fails, it gives no traceback, e.g. [here](https://github.com/openproblems-bio/openproblems/actions/runs/3205713057/jobs/5281423215) (due to being run as an external process.) This fixes that.

add rlang traceback in seurat methods

---

openproblems/tasks/_cell_cell_communication/_common/metrics/odds_ratio.py

@dbdimitrov why force methods to specify where or not the predictions are sorted when we can just sort them here?

sort matching rows after merge in cell cell comm

---

openproblems/tasks/_cell_cell_communication/_common/api.py
openproblems/tasks/_cell_cell_communication/cell_cell_communication_ligand_target/datasets/tnbc_wu2021.py
openproblems/tasks/_cell_cell_communication/cell_cell_communication_source_target/datasets/allen_brain_atlas.py

We need merge_keys available in adata in order to aggregate within methods.
Benchmark passing at https://github.com/scottgigante-immunai/openproblems/actions/runs/3323435471

make merge_keys available in adata.uns

---

CONTRIBUTING.md
EC2.md
docker/README.md

@LuckyMD want to try these instructions out and let me know how you do?

Add openproblems-cli test instructions

---

openproblems/tasks/dimensionality_reduction/metrics/nn_ranking.py

When _metrics fails, it is impossible to debug due to many computations being squashed into on NJIT function. This separates each metric into its own function, using NJIT when appropriate. See https://github.com/openproblems-bio/openproblems/actions/runs/3388609861/jobs/5633837315#step:19:2770
Passing benchmark at https://github.com/scottgigante-immunai/openproblems/actions/runs/3394490431

break up _metrics into separate functions

---

openproblems/tasks/dimensionality_reduction/methods/__init__.py
openproblems/tasks/dimensionality_reduction/methods/baseline.py

The high-dimensional PCA does well in global metrics, but poorly in local knn metrics. This baseline (200-dimensional laplacian eigenmaps) should perform well with local knn ranking metrics.

Add spectral baseline to dimensionality reduction

---

openproblems/tasks/_batch_integration/batch_integration_graph/methods/baseline.py

In immune_batch, the celltype random graph does not perform well on isolated labels F1, which is odd since it was designed for this task. The only explanation here is that louvain is combining clusters, which means the random noise is too large and thus clusters can be merged despite their clear separation. This should make the clusters tighter and thus less likely to be merged.

make celltype clusters tighter in celltype random embedding/graph

---

.github/workflows/process_results.yml

I'd like to have the CI run so we know whether the quarto pages are being rendered properly on PR

Turn off ci skip

---

openproblems/tasks/denoising/methods/__init__.py
openproblems/tasks/denoising/methods/magic.py

Reversing the order of sqrt and libnorm inexplicably improves performance. Adding this to MAGIC with explicit naming so users are aware that this is different from defaults.

add magic with reverse norm order

---

openproblems/tasks/_batch_integration/batch_integration_embed/api.py
openproblems/tasks/_batch_integration/batch_integration_embed/metrics/_utils.py
openproblems/tasks/_batch_integration/batch_integration_embed/metrics/ari.py
openproblems/tasks/_batch_integration/batch_integration_embed/metrics/cc_score.py
openproblems/tasks/_batch_integration/batch_integration_embed/metrics/graph_connectivity.py
openproblems/tasks/_batch_integration/batch_integration_embed/metrics/iso_label_f1.py
openproblems/tasks/_batch_integration/batch_integration_embed/metrics/nmi.py
openproblems/tasks/_batch_integration/batch_integration_embed/metrics/pcr.py
openproblems/tasks/_batch_integration/batch_integration_embed/metrics/utils.py
openproblems/tasks/_batch_integration/batch_integration_feature/api.py
openproblems/tasks/_batch_integration/batch_integration_feature/metrics/ari.py
openproblems/tasks/_batch_integration/batch_integration_feature/metrics/cc_score.py
openproblems/tasks/_batch_integration/batch_integration_feature/metrics/graph_connectivity.py
openproblems/tasks/_batch_integration/batch_integration_feature/metrics/iso_label_f1.py
openproblems/tasks/_batch_integration/batch_integration_feature/metrics/iso_label_sil.py
openproblems/tasks/_batch_integration/batch_integration_feature/metrics/kBET.py
openproblems/tasks/_batch_integration/batch_integration_feature/metrics/nmi.py
openproblems/tasks/_batch_integration/batch_integration_feature/metrics/pcr.py
openproblems/tasks/_batch_integration/batch_integration_feature/metrics/sil_batch.py
openproblems/tasks/_batch_integration/batch_integration_feature/metrics/silhouette.py
openproblems/tasks/_batch_integration/batch_integration_feature/metrics/utils.py
openproblems/tools/decorators.py

request (include link to passed test on NF Tower found in GitHub Actions summary: )

Don't recompute X_emb and neighborhood graph for baseline datasets

---

CHANGELOG.md
src/datasets/resource_test_scripts/cxg_immune_cell_atlas.sh

Adds the CELLxGENE immune cell atlas as a new common test resource. This is required for adding foundation models to tasks which require human data and (for at least the batch integration task) the `.obsm["X_pca"]` slot to be filled.

Add cxg_immune_cell_atlas dataset to common test resources
