openproblems/tasks/multimodal_data_integration/methods/harmonic_alignment.py, openproblems/tasks/multimodal_data_integration/methods/mnn.py, openproblems/tools/normalize.py, setup.py
=> Move scIB, rpy2, harmonicalignment, mnnpy to optional dependencies

openproblems/data/zebrafish.py
=> smallify zebrafish data

website/content/contributing/contributing.md
Just some minor typo fixes and clarifications in the contributing text.
A few things to discuss:
1. Should metrics also take in the adata objects prior to method runs? Or at least allow for more input than just 1 object?
2. methods definition: 
- output: inplace edits? Or output a list/pd.Series? Function output is not well specified here
- input: also allow covariate input. Maybe add a “…” in the function definition
3. Add "little consensus for preprocessing" ref: Nir Yosef paper on normalization (10.1016/J.CELS.2019.03.010)
=> Update contributing section text

openproblems/tasks/multimodal_data_integration/methods/mnn.py
=> use fastmnn instead of mnnpy

openproblems/data/citeseq.py, openproblems/tasks/multimodal_data_integration/datasets/__init__.py, openproblems/tasks/multimodal_data_integration/datasets/citeseq.py, openproblems/tasks/multimodal_data_integration/methods/mnn.py, setup.py
=> Add citeseq

.travis.yml, openproblems/data/scicar_chrom/__init__.py, openproblems/data/scicar_chrom/base.py, openproblems/data/scicar_chrom/mouse_kidney.py, openproblems/tasks/chromatin_potential/__init__.py, openproblems/tasks/chromatin_potential/checks.py, openproblems/tasks/chromatin_potential/datasets/__init__.py, openproblems/tasks/chromatin_potential/datasets/scicar_chrom.py, openproblems/tasks/chromatin_potential/methods/__init__.py, openproblems/tasks/chromatin_potential/methods/linear_regression.py, openproblems/tasks/chromatin_potential/metrics/__init__.py, openproblems/tasks/chromatin_potential/metrics/correlation.py, setup.py
This is the version of chromatin potential to associate ATAC with gene expression. Not sure how to test with the snakemake environment.
=> Chrom potential

openproblems/data/pancreas.py, openproblems/data/utils.py, openproblems/data/zebrafish.py
Add filtering of pancreas genes & cells. This is only really relevant for test datasets, but added throughout just in case.
This partially addresses #102
=> Remove 0 count cells or genes from pancreas dataset

.github/workflows/build_docker.yml, setup.py
addresses https://github.com/theislab/scanpy/issues/1579
=> require umap<0.5

.github/pull_request_template.md, workflow/parse_nextflow.py
=> coerce exit code to int

docker/sagemaker-example-python-3.8/Dockerfile, docker/sagemaker-example-python-3.8/kernelspec.json, docker/sagemaker-example-python-3.8/requirements.txt
=> Update 3.8 kernel

CONTRIBUTING.md, docker/openproblems-r-base/Dockerfile, docker/openproblems-r-base/requirements.txt, docker/openproblems-r-extras/Dockerfile, setup.py, workflow/Snakefile
=> block rpy2<3.4.3

.github/workflows/run_benchmark.yml
=> Remove -resume and other Nextflow tricks

.github/workflows/run_benchmark.yml, CONTRIBUTING.md
Appends first 6 characters of username to docker image tag to avoid ECR clashes
=> Use username in Docker image

openproblems/api/main.py, test/test_cli.py
=> Fix cli failing tests when metric returns 0.0 float

.github/pull_request_template.md
Updates the PR template to include the checks we will use to assess the PR
=> updated template for PR with PR evaluation checks

README.md, setup.py
* Update README.md
* Update setup.py
* Update setup.py
* Downgrade decorator
* Don't block pytest
=> Downgrade `decorator` to <5.0 (#324)

openproblems/tasks/dimensionality_reduction/methods/phate.py, openproblems/tasks/dimensionality_reduction/methods/preprocessing.py, openproblems/tasks/label_projection/methods/knn_classifier.py, openproblems/tasks/label_projection/methods/logistic_regression.py, openproblems/tasks/label_projection/methods/mlp.py, openproblems/tasks/multimodal_data_integration/methods/harmonic_alignment.py, openproblems/tasks/multimodal_data_integration/methods/mnn.py, openproblems/tasks/multimodal_data_integration/methods/procrustes.py, openproblems/tasks/multimodal_data_integration/methods/scot.py, openproblems/tools/decorators.py, openproblems/tools/normalize.py, test/test_datasets.py, test/test_tools.py
Prerequisite for https://github.com/openproblems-bio/openproblems/pull/318. In order to normalize by HVGs, we need to return a reference to the anndata object.
=> Convert normalizers to return anndata

.pre-commit-config.yaml, openproblems/tasks/dimensionality_reduction/metrics/root_mean_square_error.py, openproblems/tasks/multimodal_data_integration/metrics/mse.py, setup.py, workflow/parse_nextflow.py
=> update black 22.3.0 per https://github.com/psf/black/issues/2964

openproblems/tasks/dimensionality_reduction/methods/phate.py, openproblems/tasks/dimensionality_reduction/metrics/nn_ranking.py, openproblems/tasks/label_projection/methods/logistic_regression.py, openproblems/tasks/label_projection/methods/mlp.py, openproblems/tasks/multimodal_data_integration/methods/harmonic_alignment.py, openproblems/tasks/multimodal_data_integration/methods/procrustes.py, openproblems/tasks/multimodal_data_integration/methods/scot.py, openproblems/tasks/regulatory_effect_prediction/methods/beta.py
There's no point gumming up our [coverage metrics](https://app.codecov.io/gh/openproblems-bio/openproblems) with stuff that a) shouldn't be covered in testing (non-test parameters) or b) can't be covered in testing (njit).
=> Ignore missing coverage where appropriate

openproblems/tasks/dimensionality_reduction/api.py, openproblems/tasks/dimensionality_reduction/metrics/trustworthiness.py
Increases coverage by removing an unnecessary check.
=> Remove unnecessary check from trustworthiness metric

test/test_cli.py
=> more tests for the CLI

.github/workflows/run_benchmark.yml, docker/openproblems-github-actions/Dockerfile, docker/openproblems-github-actions/README.md, docker/openproblems-r-extras/r_requirements.txt
Adding a new docker image explicitly for github actions to use.
=> Add new github-actions container

openproblems/tasks/multimodal_data_integration/methods/scot.py
Per https://github.com/openproblems-bio/openproblems/pull/357#issuecomment-1099461170, removing SCOT unbalanced for now until someone has time to fix it.
=> Remove scot unbalanced

docker/README.md, docker/openproblems-python-batch-integration/Dockerfile, docker/openproblems-python-batch-integration/README.md, docker/openproblems-python-batch-integration/requirements.txt, docker/openproblems-r-extras/Dockerfile, docker/openproblems-r-extras/r_requirements.txt, docker/openproblems-r-extras/requirements.txt
This PR adds the docker images necessary for the batch integration task.
=> docker images separate PR

openproblems/tasks/dimensionality_reduction/datasets/__init__.py, openproblems/tasks/dimensionality_reduction/datasets/citeseq.py
CITEseq CBMC dataset in the DR task is the only thing taking 6 hours. Removing it will solve our issues temporarily.
=> Remove citeseq cbmc from DR

.cirun.yml, .github/workflows/run_tests.yml
This should fix problems with workflows hanging
=> upgrade AMI

test/test__load_data.py, test/test_datasets.py, test/test_methods.py, test/test_metrics.py, test/utils/docker.py, test/utils/git.py
Reverts openproblems-bio/openproblems#387
=> Revert "Bugfix CI"

.github/workflows/run_tests.yml, workflow/Snakefile, workflow/snakemake_tools.py
=> dirty hack to fix docker_build

openproblems/tasks/denoising/methods/alra.R, setup.py
Removing temporary fork as the fixes have been merged to the main repo.
=> require scprep v1.2

.github/workflows/process_results.yml, .github/workflows/run_tests.yml
Benchmarks failing due to https://github.com/nextflow-io/nextflow/issues/2872
=> Force nextflow v22.04.0

.github/workflows/run_tests.yml, scripts/clear_runner_diskspace.sh, workflow/parse_nextflow.py
See https://github.com/actions/virtual-environments/issues/2840
=> Clear up disk space

.github/workflows/run_tests.yml, test/test_methods.py
Reverts openproblems-bio/openproblems#442
=> Revert "remove maxfail; print durations"

openproblems/tasks/_batch_integration/batch_integration_graph/methods/__init__.py, openproblems/tasks/_batch_integration/batch_integration_graph/methods/bbknn.py
This PR both a) removes `bbknn_full_unscaled` (which I will move to a PR to re-add) and b) adds test args to a bunch of long-running batch integration methods.
=> remove bbknn_full_unscaled

.github/workflows/run_tests.yml, docker/openproblems-python-batch-integration/Dockerfile
=> Change docker version again

.github/workflows/run_tests.yml, docker/openproblems/Dockerfile
This time I think this really might fix (I hope) #457
=> use nf-openproblems 1.5

docker/openproblems-python-extras/README.md, docker/openproblems-python-extras/requirements.txt, docker/openproblems-r-extras/README.md, docker/openproblems-r-extras/requirements.txt, openproblems/tasks/label_projection/methods/__init__.py, openproblems/tasks/label_projection/methods/xgboost.py, test/docker_run.sh, test/utils/asserts.py
XGBoost performs best on this task in our internal benchmarks, so I figured I'd add it to openproblems.
=> Add xgboost to label projection

.github/workflows/run_tests.yml, docker/openproblems-r-extras/r_requirements.txt
This PR will give a better error message for dependabot PRs (see https://github.com/dependabot/dependabot-core/issues/3253)
=> Fail `run_test_benchmark` if run by dependabot

setup.py
Reverts openproblems-bio/openproblems#474
=> Revert "Update decorator requirement from <5.0 to <6.0"

openproblems/tasks/spatial_decomposition/methods/__init__.py, openproblems/tasks/spatial_decomposition/methods/destvi.py
request (include link to passed test: )
https://github.com/giovp/SingleCellOpenProblems/runs/7520650446?check_suite_focus=true
=> add destvi

test/utils/docker.py
request (include link to passed test: )
=> Fix docker unavailable error message

openproblems/tasks/spatial_decomposition/methods/nusvr.py, openproblems/tasks/spatial_decomposition/utils.py
Per https://tower.nf/orgs/openproblems-bio/workspaces/openproblems-bio/watch/2l0QkJPEKCHUCC , NuSVR is hanging with large datasets. I solved this by a) running PCA and b) setting maxiter.
Requesting review from @giovp
=> Speed up NuSVR

openproblems/tasks/spatial_decomposition/methods/cell2location.py
request (include link to passed test: https://github.com/scottgigante-immunai/openproblems/actions/runs/2959547178)
=> use fewer epochs in cell2location test mode

openproblems/tasks/spatial_decomposition/README.md, openproblems/tasks/spatial_decomposition/api.py
request (include link to passed test: https://github.com/scottgigante-immunai/openproblems/actions/runs/2959274685)
=> Require that proportions sum to 1

.github/workflows/process_results.yml, workflow/generate_website_markdown.py, workflow/parse_nextflow.py, workflow/utils.py
This skips writing both the results JSON and the readme markdown for tasks that are smaller than (1, 3, 1)
Addresses comment https://github.com/openproblems-bio/openproblems/pull/566#issuecomment-1245914132
=> Don't write results for incomplete tasks

docker/openproblems/requirements.txt
Reverts openproblems-bio/openproblems#600 due to MulticoreTSNE failure
=> Revert "Update cmake requirement from ==3.22.* to ==3.24.* in /docker/openproblems"

openproblems/tasks/dimensionality_reduction/datasets/mouse_blood_olssen_labelled.py, openproblems/tasks/dimensionality_reduction/datasets/mouse_hspc_nestorowa2016.py, openproblems/tasks/dimensionality_reduction/datasets/tenx_5k_pbmc.py
This just adds documentation about dimensions (numbers of cells, features, cell types) to the dimensionality reduction task.
request (include link to passed test: )
=> Add dimensions to dimred datasets

setup.py
Reverts openproblems-bio/openproblems#630
=> Revert "Update tabulate requirement from <0.9 to <0.10"

setup.py
Thanks to @vtraag for the new release :)
=> bump louvain to 0.8

.github/workflows/run_tests.yml
=> use codecov github action

openproblems/data/tabula_muris_senis.py, openproblems/tasks/spatial_decomposition/datasets/__init__.py, openproblems/tasks/spatial_decomposition/datasets/tabula_muris_senis.py
Batch effects in the pancreas dataset made the task too difficult. This uses 11000 cells from tabula senis instead.
=> use tabula muris senis in addition to pancreas

setup.py
Reverts openproblems-bio/openproblems#639
=> Revert "bump louvain to 0.8"

openproblems/data/tabula_muris_senis.py
Requests is a little flaky. This should fix it.
=> retry failed request

.github/workflows/process_results.yml, workflow/parse_nextflow.py, workflow/workflow_utils.py
NaNs are not correctly parsed by netlify. This converts non-finite metric outputs to strings.
=> Handle NaNs in nextflow export

.pre-commit-config.yaml, openproblems/tasks/_batch_integration/batch_integration_embed/methods/__init__.py, openproblems/tasks/_batch_integration/batch_integration_embed/methods/baseline.py, openproblems/tasks/_batch_integration/batch_integration_graph/methods/__init__.py, openproblems/tasks/_batch_integration/batch_integration_graph/methods/baseline.py, test/docker_run.sh, workflow/Snakefile
Designed to address https://github.com/openproblems-bio/openproblems/issues/685
=> add perfect celltype mixing baseline

.github/pull_request_template.md, .github/workflows/run_tests.yml
Moving all benchmark runs to tower. Running in GA is just too flaky.
=> Run test benchmark in Tower

docker/openproblems-python-batch-integration/requirements.txt
mnnpy has been resurrected! (thanks @chriscainx !)
Updating to no longer use my fork.
=> Use mnnpy from base repo

openproblems/tasks/spatial_decomposition/methods/cell2location.py
=> set num_samples=2 in test mode

.github/workflows/run_tests.yml, workflow/Snakefile, workflow/snakemake_tools.py
Docker has variable cpu utilisation due to disk and network constraints. This increases parallelism.
=> Run builds in parallel

.github/workflows/run_tests.yml
=> Build images in PR if same repo owner

docker/openproblems-r-extras/requirements.txt, docker/openproblems-r-pytorch/requirements.txt, setup.py
Fixes persistent dependency clash issues
=> Update scib louvain and igraph

docker/openproblems-r-extras/requirements.txt, docker/openproblems-r-pytorch/requirements.txt, setup.py
Reverts openproblems-bio/openproblems#739
=> Revert "Update scib louvain and igraph"

.github/workflows/process_results.yml, docker/openproblems-r-extras/r_requirements.txt, openproblems/tasks/_cell_cell_communication/_common/methods/__init__.py, openproblems/tasks/_cell_cell_communication/_common/methods/baseline.py, openproblems/tasks/_cell_cell_communication/_common/methods/liana.R, openproblems/tasks/_cell_cell_communication/_common/methods/liana.py, openproblems/tasks/_cell_cell_communication/_common/metrics/odds_ratio.py, openproblems/tasks/_cell_cell_communication/cell_cell_communication_ligand_target/methods/__init__.py, openproblems/tasks/_cell_cell_communication/cell_cell_communication_source_target/methods/__init__.py, test/test_task_cell_cell_communication.py
CCC task ligand-target random results fix & add types of aggregation.
=> Ccc aggregate + ligand-target subtask fix

openproblems/tasks/dimensionality_reduction/methods/__init__.py, openproblems/tasks/dimensionality_reduction/methods/baseline.py, openproblems/tasks/dimensionality_reduction/metrics/root_mean_square_error.py
=> [Dimensionality reduction] Fix normalization in baselines

workflow/parse_nextflow.py
Closes https://github.com/openproblems-bio/website/issues/27
Closes https://github.com/openproblems-bio/website/pull/82
=> Fix output headers order

.github/workflows/pre-commit.yml, .pre-commit-config.yaml
Bugfix for https://github.com/PyCQA/isort/issues/2077
=> Upgrade isort

openproblems/tasks/_cell_cell_communication/_common/methods/liana.py
Minor fix to logFC's decorator
=> add missing logfc decorator

.github/workflows/run_tests.yml
Uses prioritised compute queues
=> Update nf-openproblems to v1.10

openproblems/tasks/spatial_decomposition/methods/destvi.py
New try to PR. PR includes updates to destvi training procedure.
https://github.com/openproblems-bio/openproblems/issues/821
=> Destvi updated train

openproblems/tasks/spatial_decomposition/methods/destvi.py
Authored by @cane11 . Replaces #826
=> Changes in destVI code (#826)

openproblems/tasks/_batch_integration/_common/methods/baseline.py, openproblems/tasks/_batch_integration/batch_integration_embed/methods/__init__.py, openproblems/tasks/_batch_integration/batch_integration_embed/methods/baseline.py
request (include link to passed test on NF Tower found in GitHub Actions summary: )
=> jitter baseline patch

openproblems/tasks/_cell_cell_communication/_common/metrics/auprc.py, openproblems/tasks/dimensionality_reduction/methods/pca.py, openproblems/tasks/dimensionality_reduction/methods/tsne.py, openproblems/tasks/spatial_decomposition/methods/cell2location.py, test/test_core_metadata.py
Partially addresses https://github.com/openproblems-bio/website-experimental/issues/54
@vitkl we had to shorten method names for the website. Can you please confirm the description and names here are accurate for cell2location?
=> Shorten method descriptions

.github/workflows/update_website_content.yml, openproblems/api/hash.py, pytest.ini, test/test_core_cli.py, workflow/parse_metadata.py
Addresses https://github.com/openproblems-bio/website/pull/170
=> only update sha on changes

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Closes #xxxx (Replace xxxx with the GitHub issue number)
=> create v2.0.0 release

CHANGELOG.md, src/utils/extract_uns_metadata/script.py
Closes #xxxx (Replace xxxx with the GitHub issue number)
=> Fix reporting

CHANGELOG.md, src/reporting/get_method_info/script.R, src/reporting/get_metric_info/script.R, src/reporting/get_task_info/script.R, src/reporting/process_task_results/run_test.sh
* Update `get_task_info`, `get_method_info` and `get_metrics_info` comp with more info and extend output
* Fix bug in `process_task_results/run_test.sh` 
=> Update reporting components to include all links 

CODE_OF_CONDUCT.md
Closes #xxxx (Replace xxxx with the GitHub issue number)
=> Add email address to coc
